/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shout.gui;

import java.util.Properties;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import shoutboard.ejb.ShoutBoardEJBRemote;

/**
 *
 * @author ipd
 */
public class MainWindow extends javax.swing.JFrame {

    DefaultListModel<String> shoutListModel = new DefaultListModel<>();
    //interface
    ShoutBoardEJBRemote shoutService;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        try {
            
            Properties props = new Properties();
// props.load(new FileInputStream("jndi.properties"));
            props.setProperty("java.naming.factory.initial", "com.sun.enterprise.naming.SerialInitContextFactory");
           // it is  aconnection to the container
            InitialContext ctx = new InitialContext(props);
            //interdace name                // do you have a bean that implmenets that interface                                     
            shoutService = (ShoutBoardEJBRemote) ctx.lookup(ShoutBoardEJBRemote.class.getName()); //"shout.ejb.ShoutServiceRemote"); 

            initComponents();
            refreshShouts();
        } catch (NamingException ex) {
// ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error connectiong to Glassfish");
            throw new RuntimeException("Error connecting to Glassfish", ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbShout = new javax.swing.JLabel();
        btShout = new javax.swing.JButton();
        tfShout = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstShouts = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbShout.setText("Enter Shout:");

        btShout.setText("Shout!");
        btShout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShoutActionPerformed(evt);
            }
        });

        tfShout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfShoutActionPerformed(evt);
            }
        });

        lstShouts.setModel(shoutListModel);
        jScrollPane1.setViewportView(lstShouts);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbShout)
                        .addGap(18, 18, 18)
                        .addComponent(tfShout)
                        .addGap(18, 18, 18)
                        .addComponent(btShout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbShout)
                    .addComponent(btShout)
                    .addComponent(tfShout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfShoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfShoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfShoutActionPerformed

    private void btShoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShoutActionPerformed
        try {
            String shout = tfShout.getText();
            //this calls the automatix generated proxy class 
            //add shout makes the call happen in the container o the server
            //shout service is the proxy class that calls the container to tell the bean  
            shoutService.addshout(shout);
            tfShout.setText("");
            refreshShouts();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Addin shout:" + e.getMessage());
        }
    }//GEN-LAST:event_btShoutActionPerformed
    private void refreshShouts() {
        try {
            String[] shoutArray = shoutService.getAllShouts();
            shoutListModel.clear();
            for (String s : shoutArray) {
                shoutListModel.addElement(s);
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error Addin shout:" + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btShout;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbShout;
    private javax.swing.JList<String> lstShouts;
    private javax.swing.JTextField tfShout;
    // End of variables declaration//GEN-END:variables
}
